export const PRODUCTS = [
  {
    id: "personalizacja-grawer-jaspis-kiwi",
    name: "Personalizacja (Grawer)",
    price: 145,
    currency: "PLN",
    colors: ["silver", "gray"],
    material: "sterling_silver",
    images: ["./assets/images/product-12-01.png"],
    featured: false,
    categories: ["Personalizacja", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z jaspisu kiwi ze srebrną zawieszką. Delikatny, błękitno-miętowy odcień kamienia z naturalnymi inkluzjami tworzy świeżą i lekką kompozycję. Gładką zawieszkę można spersonalizować — wykonać dowolny grawer: imię, inicjały, datę lub własny symbol.",
    specs: {
      kamienie: "Jaspis kiwi",
      metal: "Srebro 925",
      waga: "0,70 g",
    },
    gallery: [
      "./assets/images/product-12-01.png",
      "./assets/images/product-12-02.png",
      "./assets/images/product-12-03.png",
    ],
  },
  {
    id: "li-love-onyx-cuff",
    name: "Bransoletka — biały agat (królik)",
    price: 180,
    currency: "PLN",
    colors: ["white"],
    material: "sterling_silver",
    images: ["./assets/images/product-01-01.png"],
    featured: true,
    categories: ["Kolekcja", "Symbole", "Personalizacja"],
    description:
      "Naturalne kamienie z białego agatu, zawieszka w kształcie królika wykonana ze srebra 925, kontur królika wykończony czarną emalią.",
    specs: {
      kamienie: "Biały agat",
      metal: "Srebro 925",
      waga: "0,71 g",
    },
    gallery: [
      "./assets/images/product-01-01.png",
      "./assets/images/product-01-02.png",
      "./assets/images/product-01-03.png",
    ],
    tags: ["cuff", "minimal"],
  },
  {
    id: "li-love-ivory-chain",
    name: "Bransoletka — Yin‑Yang (kamień księżycowy i onyks)",
    price: 310,
    currency: "PLN",
    colors: ["white", "black"],
    material: "sterling_silver",
    images: ["./assets/images/product-02-01.png"],
    featured: true,
    categories: ["Kolekcja", "Dla par", "Zestawy"],
    description:
      "Bransoletka z kamienia księżycowego i onyksu z srebrnymi zawieszkami Yin‑Yang. Kontrast jasnego kamienia księżycowego i głębokiej czerni onyksu symbolizuje harmonię przeciwieństw, a subtelne srebrne elementy dodają elegancji i znaczenia.",
    specs: {
      kamienie: "Onyks i kamienie księżycowe",
      metal: "Srebro 925",
      waga: "0,86 g",
    },
    gallery: [
      "./assets/images/product-02-01.png",
      "./assets/images/product-02-02.png",
      "./assets/images/product-02-03.png",
    ],
    tags: ["chain", "daily"],
  },
  {
    id: "li-love-rose-quartz-onyx-hearts",
    name: "Bransoletka — serca (kwarc różowy i onyks)",
    price: 320,
    currency: "PLN",
    colors: ["pink", "black"],
    material: "sterling_silver",
    images: ["./assets/images/product-03-02.png"],
    featured: true,
    categories: ["Dla par", "Kolekcja", "Personalizacja"],
    description:
      "Bransoletka z różowego kwarcu i onyksu ze srebrnymi zawieszkami w kształcie serca. Delikatny różowy kwarc w połączeniu z głęboką czernią onyksu tworzy harmonijny i elegancki kontrast. Gładkie zawieszki można spersonalizować — dodać imiona, inicjały, datę, znak zodiaku lub własny symbol.",
    specs: {
      kamienie: "Kwarc różowy i onyks",
      metal: "Srebro 925",
      waga: "1,10 g",
    },
    gallery: [
      "./assets/images/product-03-02.png",
      "./assets/images/product-03-01.png",
      "./assets/images/product-03-03.png",
    ],
    tags: ["beads", "personalization", "gift"],
  },
  {
    id: "li-love-rose-quartz-onyx-playboy",
    name: "Bransoletka — Playboy (kwarc różowy i onyks)",
    price: 330,
    currency: "PLN",
    colors: ["pink", "black"],
    material: "sterling_silver",
    images: ["./assets/images/product-04-01.png"],
    featured: true,
    categories: ["Dla par", "Kolekcja"],
    description:
      "Bransoletka z różowego kwarcu i onyksu ze srebrnymi przekładkami i zawieszkami Playboy. Delikatny różowy kwarc w połączeniu z czarnym onyksem uzupełniają srebrne kuleczki. Zawieszki w formie królików Playboy — dziewczynka z kokardką i chłopiec z muszką — nadają biżuterii zabawny i stylowy charakter.",
    specs: {
      kamienie: "Kwarc różowy i onyks",
      metal: "Srebro 925",
      waga: "1,34 g",
    },
    gallery: [
      "./assets/images/product-04-01.png",
      "./assets/images/product-04-02.png",
      "./assets/images/product-04-03.png",
    ],
    tags: ["beads", "couple", "playful"],
  },
  {
    id: "li-love-jadeite-hibiscus",
    name: "Bransoletka — hibiskus (jadeit zoito‑różowy)",
    price: 165,
    currency: "PLN",
    colors: ["pink", "gold"],
    material: "sterling_silver",
    images: ["./assets/images/product-05-01.png"],
    featured: false,
    categories: ["Natura", "Kolekcja"],
    description:
      "Bransoletka z jadeitu w odcieniach różowo‑żółtych ze srebrną zawieszką w kształcie kwiatu hibiskusa. Ciepłe kolory kamieni tworzą subtelną i radosną kompozycję, a delikatna zawieszka w formie hibiskusa nadaje biżuterii lekkości i letniego charakteru.",
    specs: {
      kamienie: "Jadeit zoito‑różowy",
      metal: "Srebro 925",
      waga: "0,70 g",
    },
    gallery: [
      "./assets/images/product-05-01.png",
      "./assets/images/product-05-02.png",
      "./assets/images/product-05-03.png",
    ],
    tags: ["beads", "nature", "summer"],
  },
  {
    id: "li-love-amber-pearls-butterfly",
    name: "Bransoletka — motyl (bursztyn i perły)",
    price: 200,
    currency: "PLN",
    colors: ["gold", "white"],
    material: "sterling_silver",
    images: ["./assets/images/product-06-01.png"],
    featured: false,
    categories: ["Natura", "Kolekcja"],
    description:
      "Bransoletka z naturalnego bursztynu i pereł ze srebrnymi przekładkami oraz centralną zawieszką w kształcie motyla. Ciepłe odcienie bursztynu pięknie łączą się z delikatnymi perłami, a subtelny motyl nadaje biżuterii lekkości i naturalnego uroku.",
    specs: {
      kamienie: "Bursztyn i perły",
      metal: "Srebro 925",
      waga: "0,70 g",
    },
    gallery: [
      "./assets/images/product-06-01.png",
      "./assets/images/product-06-02.png",
      "./assets/images/product-06-03.png",
    ],
    tags: ["beads", "nature", "summer"],
  },
  {
    id: "li-love-angelite-dalmatian-jasper-onyx",
    name: "Bransoletka — angelit (Peru), jaspis dalmatyński i onyks",
    price: 150,
    currency: "PLN",
    colors: ["black", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-07-01.png"],
    featured: false,
    categories: ["Kolekcja"],
    description:
      "Bransoletka z angelitu (Peru), jaspisu dalmatyńskiego i onyksu ze srebrnymi przekładkami. Delikatny błękit angelitu z Peru pięknie łączy się z charakterystycznym jaspisem dalmatyńskim i głęboką czernią onyksu, tworząc wyjątkową kompozycję. Srebrne elementy dodają biżuterii elegancji.",
    specs: {
      kamienie: "Onyks, jaspis dalmatyński, angelit (Peru)",
      metal: "Srebro 925",
      waga: "0,50 g",
    },
    gallery: [
      "./assets/images/product-07-01.png",
      "./assets/images/product-07-02.png",
      "./assets/images/product-07-03.png",
    ],
    tags: ["beads", "daily", "minimal"],
  },
  {
    id: "li-love-matcha-dalmatian-jasper-hematite",
    name: "Bransoletka — jaspis matcha, jaspis dalmatyński i hematyt",
    price: 160,
    currency: "PLN",
    colors: ["silver", "gray"],
    material: "sterling_silver",
    images: ["./assets/images/product-08-01.png"],
    featured: false,
    categories: ["Kolekcja"],
    description:
      "Bransoletka z jaspisu matcha, jaspisu dalmatyńskiego i hematytu ze srebrnymi przekładkami. Delikatna zieleń jaspisu matcha pięknie łączy się z charakterystycznym wzorem jaspisu dalmatyńskiego, a hematyt dodaje głębi i nowoczesnego akcentu. Srebrne elementy podkreślają elegancję biżuterii.",
    specs: {
      kamienie: "Jaspis matcha, jaspis dalmatyński, hematyt",
      metal: "Srebro 925",
      waga: "0,75 g",
    },
    gallery: [
      "./assets/images/product-08-01.png",
      "./assets/images/product-08-02.png",
      "./assets/images/product-08-03.png",
    ],
    tags: ["beads", "daily", "minimal"],
  },
  {
    id: "li-love-onyx-spider",
    name: "Bransoletka — onyks (pająk)",
    price: 145,
    currency: "PLN",
    colors: ["black", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-09-01.png"],
    featured: false,
    categories: ["Męskie"],
    description:
      "Bransoletka z fasetowanego czarnego onyksu ze srebrną zawieszką w kształcie pająka. Głęboka czerń kamienia podkreśla elegancki i wyrazisty charakter biżuterii, a subtelna zawieszka dodaje jej oryginalnego, odważnego akcentu.",
    specs: {
      kamienie: "Onyks",
      metal: "Srebro 925",
      waga: "0,55 g",
    },
    gallery: [
      "./assets/images/product-09-01.png",
      "./assets/images/product-09-02.png",
      "./assets/images/product-09-03.png",
    ],
    tags: ["beads", "mens", "minimal"],
  },
  {
    id: "li-love-black-tourmaline-mens",
    name: "Bransoletka — turmalin (czarny)",
    price: 285,
    currency: "PLN",
    colors: ["black", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-10-01.png"],
    featured: false,
    categories: ["Męskie"],
    description:
      "Bransoletka z czarnego turmalinu ze srebrnymi przekładkami. Matowa, głęboka czerń turmalinu nadaje biżuterii minimalistyczny i wyrazisty charakter, a srebrne elementy wprowadzają elegancki kontrast.",
    specs: {
      kamienie: "Turmalin",
      metal: "Srebro 925",
      waga: "2,27 g",
    },
    gallery: [
      "./assets/images/product-10-01.png",
      "./assets/images/product-10-02.png",
      "./assets/images/product-10-03.png",
    ],
    tags: ["beads", "mens", "minimal"],
  },
  {
    id: "li-love-larvikite-silver-inlay",
    name: "Bransoletka — larvikit (srebrna wstawka)",
    price: 355,
    currency: "PLN",
    colors: ["gray", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-11-01.png"],
    featured: false,
    categories: ["Męskie"],
    description:
      "Bransoletka z larvikitu z centralną srebrną wstawką. Głębokie szaro‑grafitowe odcienie larvikitu z naturalnym wzorem tworzą elegancką i wyrazistą kompozycję, a fakturowany srebrny element dodaje charakteru.",
    specs: {
      kamienie: "Larvikit",
      metal: "Srebro 925",
      waga: "5,14 g",
    },
    gallery: [
      "./assets/images/product-11-01.png",
      "./assets/images/product-11-02.png",
      "./assets/images/product-11-03.png",
    ],
    tags: ["beads", "mens", "minimal"],
  },
];

export const COLOR_META = {
  black: { label: "Czarny", swatch: "#0D0D0D" },
  gray: { label: "Szary", swatch: "#8C8C8C" },
  white: { label: "Biały", swatch: "#FFFFFF" },
  pink: { label: "Różowy", swatch: "#E9B7C6" },
  silver: { label: "Srebrny", swatch: "#E6E6E6" },
  gold: { label: "Złoty", swatch: "#D7C08A" },
};

export const MATERIAL_META = {
  stainless_steel: "Stal szlachetna",
  sterling_silver: "Srebro próby 925",
  gold_plated: "Pozłacane",
  titanium: "Tytan",
};

