export const PRODUCTS = [
  {
    id: "perly-klasyczne-grawer-dla-par",
    name: "Bransoletka — Perły (grawer)",
    price: 245,
    currency: "PLN",
    colors: ["white", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-29-01.png"],
    featured: false,
    categories: ["Klasyczne", "Personalizacja (Grawer)", "Dla par"],
    description:
      "Bransoletka z naturalnych pereł o subtelnym, perłowym połysku, wykończona elementami ze srebra oraz zawieszką w formie gładkiego kółka. Elegancka i ponadczasowa kompozycja, która doskonale pasuje zarówno do codziennych, jak i bardziej formalnych stylizacji. Perły symbolizują czystość, harmonię i klasę. Zawieszka daje możliwość personalizacji — można wykonać grawer z imieniem, inicjałami, datą lub wyjątkowym symbolem, tworząc unikalny i osobisty dodatek lub prezent.",
    specs: {
      kamienie: "Perły",
      metal: "Srebro 925",
      waga: "1,30 g",
    },
    gallery: [
      "./assets/images/product-29-01.png",
      "./assets/images/product-29-02.png",
      "./assets/images/product-29-03.png",
    ],
  },
  {
    id: "opal-rzeczny-lapa-grawer",
    name: "Bransoletka — opal rzeczny (łapa)",
    price: 150,
    currency: "PLN",
    colors: ["green", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-28-01.png"],
    featured: false,
    categories: ["Natura", "Zwierzęta"],
    description:
      "Bransoletka z naturalnego opalu rzecznego z dodatkiem kamieni w odcieniach zieleni oraz srebrną zawieszką w kształcie łapy. Delikatna, harmonijna kompozycja inspirowana naturą, idealna dla miłośników zwierząt. Opal kojarzony jest ze spokojem i równowagą, podkreślając subtelny charakter biżuterii. Zawieszkę można spersonalizować — wykonać dowolny grawer: imię, inicjały, datę lub symbol.",
    specs: {
      kamienie: "Opal (kamień rzeczny)",
      metal: "Srebro 925",
      waga: "0,67 g",
    },
    gallery: [
      "./assets/images/product-28-01.png",
      "./assets/images/product-28-02.png",
      "./assets/images/product-28-03.png",
    ],
  },
  {
    id: "awenturyn-oczy",
    name: "Bransoletka — Awenturyn",
    price: 345,
    currency: "PLN",
    colors: ["blue", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-27-01.png"],
    featured: false,
    categories: ["Męskie", "Oczy"],
    description:
      "Bransoletka z naturalnego awenturynu w odcieniach błękitu, uzupełniona ozdobnym elementem ze srebra. Harmonijna kompozycja o spokojnym, eleganckim charakterze, inspirowana naturą i kolorem nieba. Awenturyn kojarzony jest z równowagą, optymizmem i pozytywną energią. Idealna zarówno na co dzień, jak i jako subtelny akcent do stylizacji.",
    specs: {
      kamienie: "Awenturyn",
      metal: "Srebro 925",
      waga: "5,14 g",
    },
    gallery: [
      "./assets/images/product-27-01.png",
      "./assets/images/product-27-02.png",
      "./assets/images/product-27-03.png",
    ],
  },
  {
    id: "grawer-akwamaryn",
    name: "Bransoletka — Akwamaryn (grawer)",
    price: 170,
    currency: "PLN",
    colors: ["blue", "beige", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-26-01.png"],
    featured: false,
    categories: ["Personalizacja", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z naturalnego akwamarynu w delikatnych, pastelowych odcieniach błękitu i jasnego beżu, wykończona srebrnym elementem. Lekka i subtelna kompozycja inspirowana spokojem morza i natury. Akwamaryn kojarzony jest z harmonią, wyciszeniem i przejrzystością myśli. Idealna jako codzienny dodatek lub prezent. Istnieje możliwość personalizacji — wykonania graweru z imieniem, inicjałami, datą lub symbolem.",
    specs: {
      kamienie: "Akwamaryn",
      metal: "Srebro 925",
      waga: "0,68 g",
    },
    gallery: [
      "./assets/images/product-26-01.png",
      "./assets/images/product-26-02.png",
      "./assets/images/product-26-03.png",
    ],
  },
  {
    id: "bronzyt-oczy",
    name: "Bransoletka — Bronzyt",
    price: 375,
    currency: "PLN",
    colors: ["brown", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-25-01.png"],
    featured: false,
    categories: ["Męskie", "Oczy"],
    description:
      "Bransoletka z naturalnego bronzytu w ciepłych, drewnianych odcieniach brązu, uzupełniona ozdobnym elementem ze srebra. Surowa, wyrazista kompozycja inspirowana naturą, idealna dla osób ceniących minimalistyczny i męski styl. Bronzyt kojarzony jest z siłą, stabilnością i pewnością siebie. Doskonała na co dzień jako stylowy, uniwersalny dodatek.",
    specs: {
      kamienie: "Bronzyt",
      metal: "Srebro 925",
      waga: "5,14 g",
    },
    gallery: [
      "./assets/images/product-25-01.png",
      "./assets/images/product-25-02.png",
      "./assets/images/product-25-03.png",
    ],
  },
  {
    id: "grawer-jaspis-pasiasty",
    name: "Bransoletka — Jaspis pasiasty (grawer)",
    price: 150,
    currency: "PLN",
    colors: ["brown", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-24-01.png"],
    featured: false,
    categories: ["Personalizacja", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z jaspisu pasiastego ze srebrną zawieszką. Naturalna, spokojna kompozycja w odcieniach brązu. Jaspis wspiera równowagę i wytrwałość. Zawieszkę można spersonalizować — wykonać dowolny grawer: imię, inicjały, datę lub własny symbol.",
    specs: {
      kamienie: "Jaspis pasiasty",
      metal: "Srebro 925",
      waga: "0,60 g",
    },
    gallery: [
      "./assets/images/product-24-01.png",
      "./assets/images/product-24-02.png",
      "./assets/images/product-24-03.png",
    ],
  },
  {
    id: "baran-granat",
    name: "Bransoletka — Baran",
    price: 160,
    currency: "PLN",
    colors: ["red", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-23-01.png"],
    featured: false,
    categories: ["Znaki zodiaku", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z granatu ze srebrną zawieszką. Srebrna zawieszka z symbolem Barana podkreśla odwagę, determinację i silny charakter tego znaku. Granat wzmacnia energię Barana — dodaje pasji, pewności siebie i motywacji do działania, jednocześnie chroniąc i stabilizując emocje.",
    specs: {
      kamienie: "Granat",
      metal: "Srebro 925",
      waga: "0,53 g",
    },
    gallery: [
      "./assets/images/product-23-01.png",
      "./assets/images/product-23-02.png",
      "./assets/images/product-23-03.png",
    ],
  },
  {
    id: "lew-rozowy-kwarc-masa-perlowa",
    name: "Bransoletka — Lew",
    price: 190,
    currency: "PLN",
    colors: ["pink", "white", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-22-01.png"],
    featured: false,
    categories: ["Znaki zodiaku", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z różowego kwarcu i masy perłowej ze srebrną zawieszką serca z symbolem Lwa podkreśla siłę, pewność siebie i naturalny magnetyzm tego znaku. Różowy kwarc wnosi do energii Lwa równowagę — uczy delikatności, miłości i harmonii w relacjach. Masa perłowa dodaje spokoju, intuicji i wewnętrznego wyciszenia, tworząc idealne dopełnienie dla ognistej natury Lwa.",
    specs: {
      kamienie: "Kwarc różowy, masa perłowa",
      metal: "Srebro 925",
      waga: "0,98 g",
    },
    gallery: ["./assets/images/product-22-01.png", "./assets/images/product-22-02.png"],
  },
  {
    id: "grawer-kwarc-z-turmalinem",
    name: "Bransoletka — Kwarc z turmalinem (grawer)",
    price: 160,
    currency: "PLN",
    colors: ["gray", "black", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-21-01.png"],
    featured: false,
    categories: ["Personalizacja", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z kwarcu z turmalinem ze srebrną wstawką i zawieszką. Jasny kwarc z naturalnymi czarnymi inkluzjami tworzy minimalistyczną i elegancką kompozycję. Zawieszkę można spersonalizować — wykonać dowolny grawer: imię, inicjały, datę lub własny symbol.",
    specs: {
      kamienie: "Kwarc z turmalinem",
      metal: "Srebro 925",
      waga: "0,58 g",
    },
    gallery: [
      "./assets/images/product-21-01.png",
      "./assets/images/product-21-02.png",
      "./assets/images/product-21-03.png",
    ],
  },
  {
    id: "kocham-warszawe",
    name: "Bransoletka — Kocham Warszawę",
    price: 160,
    currency: "PLN",
    colors: ["red", "white", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-20-01.png"],
    featured: false,
    categories: ["Miasta", "Kolekcja"],
    description:
      "Bransoletka z czerwonego i białego howlitu ze srebrną zawieszką w kształcie serca. Kontrastowe kolory kamieni tworzą wyrazistą kompozycję, a napis „Kocham Warszawę” nadaje biżuterii wyjątkowego, osobistego charakteru.",
    specs: {
      kamienie: "Howlit biały, czerwony syntetyczny",
      metal: "Srebro 925",
      waga: "0,58 g",
    },
    gallery: ["./assets/images/product-20-01.png"],
  },
  {
    id: "dualizm-blizniat",
    name: "Bransoletka — Dualizm Bliźniąt",
    price: 185,
    currency: "PLN",
    colors: ["gray", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-19-01.png"],
    featured: false,
    categories: ["Znaki zodiaku", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z szarego agatu pasiastego ze srebrną zawieszką ze znakiem zodiaku Bliźnięta. Szary agat pasiasty symbolizuje równowagę, ochronę i klarowność myśli, wspierając wewnętrzną stabilność. Znak Bliźniąt oznacza komunikatywność, elastyczność i wielowymiarowość osobowości, czyniąc tę bransoletkę wyjątkowym talizmanem harmonii i wyrażania siebie.",
    specs: {
      kamienie: "Agat szary pasiasty",
      metal: "Srebro 925",
      waga: "0,51 g",
    },
    gallery: [
      "./assets/images/product-19-01.png",
      "./assets/images/product-19-02.png",
      "./assets/images/product-19-03.png",
    ],
  },
  {
    id: "pudrowy-awenturyn-grawer",
    name: "Bransoletka — Pudrowy awenturyn (grawer)",
    price: 180,
    currency: "PLN",
    colors: ["pink", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-18-01.png"],
    featured: false,
    categories: ["Personalizacja", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z awenturynu ze srebrnymi przekładkami i zawieszką. Delikatne, pudrowo-brzoskwiniowe odcienie kamienia tworzą lekką i harmonijną kompozycję. Awenturyn uznawany jest za kamień szczęścia, inspiracji i nowych możliwości. Zawieszkę można spersonalizować — wykonać dowolny grawer: imię, inicjały, datę lub własny symbol.",
    specs: {
      kamienie: "Awenturin",
      metal: "Srebro 925",
      waga: "1,12 g",
    },
    gallery: [
      "./assets/images/product-18-01.png",
      "./assets/images/product-18-02.png",
      "./assets/images/product-18-03.png",
    ],
  },
  {
    id: "grawer-kwarc-rozowy",
    name: "Bransoletka — kwarc różowy (grawer)",
    price: 140,
    currency: "PLN",
    colors: ["pink", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-17-01.png"],
    featured: false,
    categories: ["Personalizacja", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z różowego kwarcu ze srebrną zawieszką. Różowy kwarc symbolizuje miłość, czułość i wewnętrzną harmonię. Gładką zawieszkę można spersonalizować — wykonać dowolny grawer: imię, inicjały, datę, znak zodiaku lub własny symbol.",
    specs: {
      kamienie: "Kwarc różowy",
      metal: "Srebro 925",
      waga: "0,46 g",
    },
    gallery: [
      "./assets/images/product-17-01.png",
      "./assets/images/product-17-02.png",
      "./assets/images/product-17-03.png",
    ],
  },
  {
    id: "jaspis-niebieski-ozdobna-przekladka",
    name: "Bransoletka — jaspis niebieski (ozdobna przekładka)",
    price: 250,
    currency: "PLN",
    colors: ["blue", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-16-01.png"],
    featured: false,
    categories: ["Kolekcja"],
    description:
      "Bransoletka z niebieskiego jaspisu z ozdobną srebrną przekładką z kamieniami. Intensywne turkusowo-ziemiste odcienie jaspisu symbolizują równowagę, pewność siebie i wewnętrzną stabilność. Centralny element z niebieskimi kamieniami dodaje wyrazistości i nadaje biżuterii wyjątkowego charakteru.",
    specs: {
      kamienie: "Jaspis niebieski",
      metal: "Srebro 925",
      waga: "2,30 g",
    },
    gallery: [
      "./assets/images/product-16-01.png",
      "./assets/images/product-16-02.png",
      "./assets/images/product-16-03.png",
    ],
  },
  {
    id: "ksiezycowy-rak",
    name: "Bransoletka — Księżycowy Rak",
    price: 160,
    currency: "PLN",
    colors: ["white", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-15-01.png"],
    featured: false,
    categories: ["Znaki zodiaku", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z białego kamienia księżycowego ze srebrną zawieszką ze znakiem zodiaku Rak. Kamień księżycowy wzmacnia intuicję, harmonię wewnętrzną i równowagę emocjonalną. Znak Raka symbolizuje wrażliwość, troskę oraz silną więź z domem i bliskimi, czyniąc tę bransoletkę wyjątkowym talizmanem.",
    specs: {
      kamienie: "Kamień księżycowy",
      metal: "Srebro 925",
      waga: "0,54 g",
    },
    gallery: [
      "./assets/images/product-15-01.png",
      "./assets/images/product-15-02.png",
      "./assets/images/product-15-03.png",
    ],
  },
  {
    id: "sloneczny-cytryn",
    name: "Bransoletka — Słoneczny Cytryn",
    price: 160,
    currency: "PLN",
    colors: ["gold", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-14-01.png"],
    featured: false,
    categories: ["Kolekcja", "Natura"],
    description:
      "Bransoletka z cytrynu ze srebrnymi przekładkami. Ciepłe, złocisto-miodowe odcienie cytrynu tworzą jasną i energetyczną kompozycję. Cytryn uważany jest za kamień obfitości i dobrobytu, przyciągający szczęście oraz sukces finansowy. Srebrne elementy dodają elegancji i harmonii.",
    specs: {
      kamienie: "Cytryn",
      metal: "Srebro 925",
      waga: "0,57 g",
    },
    gallery: [
      "./assets/images/product-14-01.png",
      "./assets/images/product-14-02.png",
      "./assets/images/product-14-03.png",
    ],
  },
  {
    id: "grawer-ametyst",
    name: "Bransoletka — ametyst (grawer)",
    price: 160,
    currency: "PLN",
    colors: ["silver", "purple"],
    material: "sterling_silver",
    images: ["./assets/images/product-13-01.png"],
    featured: false,
    categories: ["Personalizacja", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z ametystu ze srebrną zawieszką. Głębokie fioletowe i naturalne, ziemiste odcienie kamienia tworzą wyjątkową, tajemniczą kompozycję. Gładką zawieszkę można spersonalizować — wykonać dowolny grawer: imię, inicjały, datę lub własny symbol.",
    specs: {
      kamienie: "Ametyst",
      metal: "Srebro 925",
      waga: "0,99 g",
    },
    gallery: [
      "./assets/images/product-13-01.png",
      "./assets/images/product-13-02.png",
      "./assets/images/product-13-03.png",
    ],
  },
  {
    id: "personalizacja-grawer-jaspis-kiwi",
    name: "Bransoletka — jaspis kiwi (grawer)",
    price: 145,
    currency: "PLN",
    colors: ["silver", "gray"],
    material: "sterling_silver",
    images: ["./assets/images/product-12-01.png"],
    featured: false,
    categories: ["Personalizacja", "Kolekcja", "Symbole"],
    description:
      "Bransoletka z jaspisu kiwi ze srebrną zawieszką. Delikatny, błękitno-miętowy odcień kamienia z naturalnymi inkluzjami tworzy świeżą i lekką kompozycję. Gładką zawieszkę można spersonalizować — wykonać dowolny grawer: imię, inicjały, datę lub własny symbol.",
    specs: {
      kamienie: "Jaspis kiwi",
      metal: "Srebro 925",
      waga: "0,70 g",
    },
    gallery: [
      "./assets/images/product-12-01.png",
      "./assets/images/product-12-02.png",
      "./assets/images/product-12-03.png",
    ],
  },
  {
    id: "li-love-onyx-cuff",
    name: "Bransoletka — biały agat (królik)",
    price: 180,
    currency: "PLN",
    colors: ["white"],
    material: "sterling_silver",
    images: ["./assets/images/product-01-01.png"],
    featured: true,
    categories: ["Kolekcja", "Symbole", "Personalizacja"],
    description:
      "Naturalne kamienie z białego agatu, zawieszka w kształcie królika wykonana ze srebra 925, kontur królika wykończony czarną emalią.",
    specs: {
      kamienie: "Biały agat",
      metal: "Srebro 925",
      waga: "0,71 g",
    },
    gallery: [
      "./assets/images/product-01-01.png",
      "./assets/images/product-01-02.png",
      "./assets/images/product-01-03.png",
    ],
    tags: ["cuff", "minimal"],
  },
  {
    id: "li-love-ivory-chain",
    name: "Bransoletka — Yin‑Yang (kamień księżycowy i onyks)",
    price: 310,
    currency: "PLN",
    colors: ["white", "black"],
    material: "sterling_silver",
    images: ["./assets/images/product-02-01.png"],
    featured: true,
    categories: ["Kolekcja", "Dla par", "Zestawy"],
    description:
      "Bransoletka z kamienia księżycowego i onyksu z srebrnymi zawieszkami Yin‑Yang. Kontrast jasnego kamienia księżycowego i głębokiej czerni onyksu symbolizuje harmonię przeciwieństw, a subtelne srebrne elementy dodają elegancji i znaczenia.",
    specs: {
      kamienie: "Onyks i kamienie księżycowe",
      metal: "Srebro 925",
      waga: "0,86 g",
    },
    gallery: [
      "./assets/images/product-02-01.png",
      "./assets/images/product-02-02.png",
      "./assets/images/product-02-03.png",
    ],
    tags: ["chain", "daily"],
  },
  {
    id: "li-love-rose-quartz-onyx-hearts",
    name: "Bransoletka — serca (kwarc różowy i onyks)",
    price: 320,
    currency: "PLN",
    colors: ["pink", "black"],
    material: "sterling_silver",
    images: ["./assets/images/product-03-02.png"],
    featured: true,
    categories: ["Dla par", "Kolekcja", "Personalizacja"],
    description:
      "Bransoletka z różowego kwarcu i onyksu ze srebrnymi zawieszkami w kształcie serca. Delikatny różowy kwarc w połączeniu z głęboką czernią onyksu tworzy harmonijny i elegancki kontrast. Gładkie zawieszki można spersonalizować — dodać imiona, inicjały, datę, znak zodiaku lub własny symbol.",
    specs: {
      kamienie: "Kwarc różowy i onyks",
      metal: "Srebro 925",
      waga: "1,10 g",
    },
    gallery: [
      "./assets/images/product-03-02.png",
      "./assets/images/product-03-01.png",
      "./assets/images/product-03-03.png",
    ],
    tags: ["beads", "personalization", "gift"],
  },
  {
    id: "li-love-rose-quartz-onyx-playboy",
    name: "Bransoletka — Playboy (kwarc różowy i onyks)",
    price: 330,
    currency: "PLN",
    colors: ["pink", "black"],
    material: "sterling_silver",
    images: ["./assets/images/product-04-01.png"],
    featured: true,
    categories: ["Dla par", "Kolekcja"],
    description:
      "Bransoletka z różowego kwarcu i onyksu ze srebrnymi przekładkami i zawieszkami Playboy. Delikatny różowy kwarc w połączeniu z czarnym onyksem uzupełniają srebrne kuleczki. Zawieszki w formie królików Playboy — dziewczynka z kokardką i chłopiec z muszką — nadają biżuterii zabawny i stylowy charakter.",
    specs: {
      kamienie: "Kwarc różowy i onyks",
      metal: "Srebro 925",
      waga: "1,34 g",
    },
    gallery: [
      "./assets/images/product-04-01.png",
      "./assets/images/product-04-02.png",
      "./assets/images/product-04-03.png",
    ],
    tags: ["beads", "couple", "playful"],
  },
  {
    id: "li-love-jadeite-hibiscus",
    name: "Bransoletka — hibiskus (jadeit zoito‑różowy)",
    price: 165,
    currency: "PLN",
    colors: ["pink", "gold"],
    material: "sterling_silver",
    images: ["./assets/images/product-05-01.png"],
    featured: false,
    categories: ["Natura", "Kolekcja"],
    description:
      "Bransoletka z jadeitu w odcieniach różowo‑żółtych ze srebrną zawieszką w kształcie kwiatu hibiskusa. Ciepłe kolory kamieni tworzą subtelną i radosną kompozycję, a delikatna zawieszka w formie hibiskusa nadaje biżuterii lekkości i letniego charakteru.",
    specs: {
      kamienie: "Jadeit zoito‑różowy",
      metal: "Srebro 925",
      waga: "0,70 g",
    },
    gallery: [
      "./assets/images/product-05-01.png",
      "./assets/images/product-05-02.png",
      "./assets/images/product-05-03.png",
    ],
    tags: ["beads", "nature", "summer"],
  },
  {
    id: "li-love-amber-pearls-butterfly",
    name: "Bransoletka — motyl (bursztyn i perły)",
    price: 200,
    currency: "PLN",
    colors: ["gold", "white"],
    material: "sterling_silver",
    images: ["./assets/images/product-06-01.png"],
    featured: false,
    categories: ["Natura", "Kolekcja"],
    description:
      "Bransoletka z naturalnego bursztynu i pereł ze srebrnymi przekładkami oraz centralną zawieszką w kształcie motyla. Ciepłe odcienie bursztynu pięknie łączą się z delikatnymi perłami, a subtelny motyl nadaje biżuterii lekkości i naturalnego uroku.",
    specs: {
      kamienie: "Bursztyn i perły",
      metal: "Srebro 925",
      waga: "0,70 g",
    },
    gallery: [
      "./assets/images/product-06-01.png",
      "./assets/images/product-06-02.png",
      "./assets/images/product-06-03.png",
    ],
    tags: ["beads", "nature", "summer"],
  },
  {
    id: "li-love-angelite-dalmatian-jasper-onyx",
    name: "Bransoletka — angelit (Peru), jaspis dalmatyński i onyks",
    price: 150,
    currency: "PLN",
    colors: ["black", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-07-01.png"],
    featured: false,
    categories: ["Kolekcja"],
    description:
      "Bransoletka z angelitu (Peru), jaspisu dalmatyńskiego i onyksu ze srebrnymi przekładkami. Delikatny błękit angelitu z Peru pięknie łączy się z charakterystycznym jaspisem dalmatyńskim i głęboką czernią onyksu, tworząc wyjątkową kompozycję. Srebrne elementy dodają biżuterii elegancji.",
    specs: {
      kamienie: "Onyks, jaspis dalmatyński, angelit (Peru)",
      metal: "Srebro 925",
      waga: "0,50 g",
    },
    gallery: [
      "./assets/images/product-07-01.png",
      "./assets/images/product-07-02.png",
      "./assets/images/product-07-03.png",
    ],
    tags: ["beads", "daily", "minimal"],
  },
  {
    id: "li-love-matcha-dalmatian-jasper-hematite",
    name: "Bransoletka — jaspis matcha, jaspis dalmatyński i hematyt",
    price: 160,
    currency: "PLN",
    colors: ["silver", "gray"],
    material: "sterling_silver",
    images: ["./assets/images/product-08-01.png"],
    featured: false,
    categories: ["Kolekcja"],
    description:
      "Bransoletka z jaspisu matcha, jaspisu dalmatyńskiego i hematytu ze srebrnymi przekładkami. Delikatna zieleń jaspisu matcha pięknie łączy się z charakterystycznym wzorem jaspisu dalmatyńskiego, a hematyt dodaje głębi i nowoczesnego akcentu. Srebrne elementy podkreślają elegancję biżuterii.",
    specs: {
      kamienie: "Jaspis matcha, jaspis dalmatyński, hematyt",
      metal: "Srebro 925",
      waga: "0,75 g",
    },
    gallery: [
      "./assets/images/product-08-01.png",
      "./assets/images/product-08-02.png",
      "./assets/images/product-08-03.png",
    ],
    tags: ["beads", "daily", "minimal"],
  },
  {
    id: "li-love-onyx-spider",
    name: "Bransoletka — onyks (pająk)",
    price: 145,
    currency: "PLN",
    colors: ["black", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-09-01.png"],
    featured: false,
    categories: ["Męskie"],
    description:
      "Bransoletka z fasetowanego czarnego onyksu ze srebrną zawieszką w kształcie pająka. Głęboka czerń kamienia podkreśla elegancki i wyrazisty charakter biżuterii, a subtelna zawieszka dodaje jej oryginalnego, odważnego akcentu.",
    specs: {
      kamienie: "Onyks",
      metal: "Srebro 925",
      waga: "0,55 g",
    },
    gallery: [
      "./assets/images/product-09-01.png",
      "./assets/images/product-09-02.png",
      "./assets/images/product-09-03.png",
    ],
    tags: ["beads", "mens", "minimal"],
  },
  {
    id: "li-love-black-tourmaline-mens",
    name: "Bransoletka — turmalin (czarny)",
    price: 285,
    currency: "PLN",
    colors: ["black", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-10-01.png"],
    featured: false,
    categories: ["Męskie"],
    description:
      "Bransoletka z czarnego turmalinu ze srebrnymi przekładkami. Matowa, głęboka czerń turmalinu nadaje biżuterii minimalistyczny i wyrazisty charakter, a srebrne elementy wprowadzają elegancki kontrast.",
    specs: {
      kamienie: "Turmalin",
      metal: "Srebro 925",
      waga: "2,27 g",
    },
    gallery: [
      "./assets/images/product-10-01.png",
      "./assets/images/product-10-02.png",
      "./assets/images/product-10-03.png",
    ],
    tags: ["beads", "mens", "minimal"],
  },
  {
    id: "li-love-larvikite-silver-inlay",
    name: "Bransoletka — larvikit (srebrna wstawka)",
    price: 355,
    currency: "PLN",
    colors: ["gray", "silver"],
    material: "sterling_silver",
    images: ["./assets/images/product-11-01.png"],
    featured: false,
    categories: ["Męskie"],
    description:
      "Bransoletka z larvikitu z centralną srebrną wstawką. Głębokie szaro‑grafitowe odcienie larvikitu z naturalnym wzorem tworzą elegancką i wyrazistą kompozycję, a fakturowany srebrny element dodaje charakteru.",
    specs: {
      kamienie: "Larvikit",
      metal: "Srebro 925",
      waga: "5,14 g",
    },
    gallery: [
      "./assets/images/product-11-01.png",
      "./assets/images/product-11-02.png",
      "./assets/images/product-11-03.png",
    ],
    tags: ["beads", "mens", "minimal"],
  },
];

export const COLOR_META = {
  black: { label: "Czarny", swatch: "#0D0D0D" },
  gray: { label: "Szary", swatch: "#8C8C8C" },
  white: { label: "Biały", swatch: "#FFFFFF" },
  pink: { label: "Różowy", swatch: "#E9B7C6" },
  silver: { label: "Srebrny", swatch: "#E6E6E6" },
  gold: { label: "Złoty", swatch: "#D7C08A" },
};

export const MATERIAL_META = {
  stainless_steel: "Stal szlachetna",
  sterling_silver: "Srebro próby 925",
  gold_plated: "Pozłacane",
  titanium: "Tytan",
};

